### ISSUE TITLE
images in Markdown content fail to render ..

### ISSUE THREAD

**Issue by gavineadie** [twostraws/IgniteSamples#15]
In the MD article "swift-against-humanity.md" there are references to images of the form:
```
![Black card: The secret to . . . unwrapped optionals.](/images/sah1.jpg)
```
but the [rendered page](https://ignitesamples.hackingwithswift.com/article/swift-against-humanity/) fails to display them.  The image link is `https://ignitesamples.hackingwithswift.com/images/sah1.jpg` (404).

I wanted to include images in my `*.md` files but couldn't find a way.  I wasn't sure if I had missed the mechanism or bumped into an Ignite oversight, so I read over IgniteSample.  Since it suffers also, I'm absolving myself!  I know this a busy week (for you, @twostraws, and me, same reason), so I'm not going to devise a fix soon.  Just wanted it on record for alter attention.

**Comment by twostraws** [comment]
Is that just me forgetting to include the images in the repository? Might be easily rectified 🙂

**Comment by gavineadie** [comment]
I'm going to close this issue because it's more complicated than I first thought and, when I feel on more solid ground, I'll open an issue next week at the _Ignite_ repo for others to see, consider and opine.
