### ISSUE TITLE
Buttons example link is broken

### ISSUE THREAD

**Issue by ezefranca** [twostraws/IgniteSamples#4]
First of all, congratulations and thanks for the project! A nice addition to our tool belt!

The example of buttons is broken, [https://ignitesamples.hackingwithswift.com/button-examples](https://ignitesamples.hackingwithswift.com/button-examples)

Probably, maybe the code is empty.
https://github.com/twostraws/IgniteSamples/blob/main/Sources/Pages/Examples/ButtonExamples.swift

**Comment by twostraws** [comment]
This is now corrected – thank you!
